/* ============================================
   AI DZ CHECK - Main Script
   AI Content Detection with multi-engine analysis
   ============================================ */

// ==================== TRANSLATIONS ====================
var currentLang = localStorage.getItem('aidzcheck_lang') || 'en';

var TRANSLATIONS = {
    en: {
        nav_features: 'Features',
        nav_how: 'How it works',
        subtitle: 'Detect AI-generated content — images, videos, and audio — with advanced analysis',
        upload_text: 'Drag & drop your file here or click to browse',
        upload_hint: 'Supports: Images (JPG, PNG, WebP), Videos (MP4, AVI), Audio (MP3, WAV)',
        btn_browse: 'Browse Files',
        helper_text: 'Max file size: 50MB — Analysis uses multiple AI detection engines',
        badge_image: 'Images',
        badge_video: 'Videos',
        badge_audio: 'Audio',
        badge_deepfake: 'Deepfake',
        badge_metadata: 'Metadata',
        badge_reverse: 'Reverse Search',
        analysis_title: 'Analyzing Content...',
        step_api_title: 'Deepfake Detection API',
        step_api_desc: 'Analyzing with primary AI detection engine',
        step_deepguard_title: 'DeepGuard Analysis',
        step_deepguard_desc: 'Secondary verification with DeepGuard engine',
        step_meta_title: 'Metadata Inspection',
        step_meta_desc: 'Checking file metadata for AI generation signatures',
        step_reverse_title: 'Reverse Search',
        step_reverse_desc: 'Searching for original sources online',
        step_compare_title: 'Results Comparison',
        step_compare_desc: 'Cross-referencing all analysis results',
        how_title: 'How it works',
        how_step1_title: '1. Upload Content',
        how_step1_desc: 'Upload an image, video, or audio file you want to verify',
        how_step2_title: '2. AI Analysis',
        how_step2_desc: 'Multiple AI engines analyze the content for signs of artificial generation',
        how_step3_title: '3. Get Report',
        how_step3_desc: 'Receive a detailed report with confidence scores from all detection methods',
        footer_copy: '\u00A9 2025 AI DZ CHECK. All rights reserved.',
        footer_dev: '\u062a\u0637\u0648\u064a\u0631 : ',
        ai_probability: 'AI Generation Probability',
        report_title: 'Detailed Report',
        report_api: 'Deepfake Detection API',
        report_deepguard: 'DeepGuard',
        report_metadata: 'Metadata Analysis',
        report_reverse: 'Reverse Search',
        comparison_title: 'Cross-Analysis Summary',
        btn_download_report: 'Download Report',
        btn_new_analysis: 'New Analysis',
        verdict_ai: 'AI-Generated Content Detected',
        verdict_real: 'Authentic Content',
        verdict_uncertain: 'Inconclusive Results',
        verdict_ai_sub: 'Multiple analysis engines indicate this content was likely generated by AI',
        verdict_real_sub: 'Analysis suggests this content is authentic and not AI-generated',
        verdict_uncertain_sub: 'Results are mixed — further manual verification is recommended',
        toast_uploading: 'Processing file...',
        toast_complete: 'Analysis complete!',
        toast_error: 'Error processing file',
        toast_too_large: 'File too large. Max size: 50MB',
        toast_invalid: 'Invalid file type. Use images, videos, or audio files',
        pwa_install_text: 'Install app for a better experience',
        meta_filename: 'File Name',
        meta_filesize: 'File Size',
        meta_filetype: 'File Type',
        meta_dimensions: 'Dimensions',
        meta_modified: 'Last Modified',
        meta_software: 'Software',
        meta_ai_markers: 'AI Markers',
        meta_exif: 'EXIF Data',
        confidence: 'Confidence',
        result_label: 'Result',
        sources_found: 'Sources Found',
        match_score: 'Match Score',
        analysis_method: 'Method',
        engines_agree: 'engines agree on the verdict',
        consensus: 'Consensus'
    },
    ar: {
        nav_features: '\u0627\u0644\u0645\u0645\u064a\u0632\u0627\u062a',
        nav_how: '\u0643\u064a\u0641 \u064a\u0639\u0645\u0644',
        subtitle: '\u0627\u0643\u062a\u0634\u0641 \u0627\u0644\u0645\u062d\u062a\u0648\u0649 \u0627\u0644\u0645\u0648\u0644\u062f \u0628\u0627\u0644\u0630\u0643\u0627\u0621 \u0627\u0644\u0627\u0635\u0637\u0646\u0627\u0639\u064a \u2014 \u0635\u0648\u0631\u060c \u0641\u064a\u062f\u064a\u0648\u060c \u0648\u0635\u0648\u062a \u2014 \u0628\u062a\u062d\u0644\u064a\u0644 \u0645\u062a\u0642\u062f\u0645',
        upload_text: '\u0627\u0633\u062d\u0628 \u0648\u0623\u0641\u0644\u062a \u0627\u0644\u0645\u0644\u0641 \u0647\u0646\u0627 \u0623\u0648 \u0627\u0646\u0642\u0631 \u0644\u0644\u062a\u0635\u0641\u062d',
        upload_hint: '\u064a\u062f\u0639\u0645: \u0635\u0648\u0631 (JPG, PNG, WebP)\u060c \u0641\u064a\u062f\u064a\u0648 (MP4, AVI)\u060c \u0635\u0648\u062a (MP3, WAV)',
        btn_browse: '\u062a\u0635\u0641\u062d \u0627\u0644\u0645\u0644\u0641\u0627\u062a',
        helper_text: '\u0627\u0644\u062d\u062c\u0645 \u0627\u0644\u0623\u0642\u0635\u0649: 50MB \u2014 \u0627\u0644\u062a\u062d\u0644\u064a\u0644 \u064a\u0633\u062a\u062e\u062f\u0645 \u0645\u062d\u0631\u0643\u0627\u062a \u0643\u0634\u0641 \u0645\u062a\u0639\u062f\u062f\u0629',
        badge_image: '\u0635\u0648\u0631',
        badge_video: '\u0641\u064a\u062f\u064a\u0648',
        badge_audio: '\u0635\u0648\u062a',
        badge_deepfake: '\u062f\u064a\u0628\u0641\u064a\u0643',
        badge_metadata: '\u0628\u064a\u0627\u0646\u0627\u062a \u0648\u0635\u0641\u064a\u0629',
        badge_reverse: '\u0628\u062d\u062b \u0639\u0643\u0633\u064a',
        analysis_title: '\u062c\u0627\u0631\u064a \u062a\u062d\u0644\u064a\u0644 \u0627\u0644\u0645\u062d\u062a\u0648\u0649...',
        step_api_title: '\u0648\u0627\u062c\u0647\u0629 \u0643\u0634\u0641 \u0627\u0644\u062a\u0632\u064a\u064a\u0641 \u0627\u0644\u0639\u0645\u064a\u0642',
        step_api_desc: '\u0627\u0644\u062a\u062d\u0644\u064a\u0644 \u0628\u0645\u062d\u0631\u0643 \u0627\u0644\u0643\u0634\u0641 \u0627\u0644\u0631\u0626\u064a\u0633\u064a',
        step_deepguard_title: '\u062a\u062d\u0644\u064a\u0644 DeepGuard',
        step_deepguard_desc: '\u0627\u0644\u062a\u062d\u0642\u0642 \u0627\u0644\u062b\u0627\u0646\u0648\u064a \u0628\u0645\u062d\u0631\u0643 DeepGuard',
        step_meta_title: '\u0641\u062d\u0635 \u0627\u0644\u0628\u064a\u0627\u0646\u0627\u062a \u0627\u0644\u0648\u0635\u0641\u064a\u0629',
        step_meta_desc: '\u0641\u062d\u0635 \u0628\u064a\u0627\u0646\u0627\u062a \u0627\u0644\u0645\u0644\u0641 \u0644\u0644\u0628\u062d\u062b \u0639\u0646 \u062a\u0648\u0642\u064a\u0639\u0627\u062a \u0627\u0644\u0630\u0643\u0627\u0621 \u0627\u0644\u0627\u0635\u0637\u0646\u0627\u0639\u064a',
        step_reverse_title: '\u0627\u0644\u0628\u062d\u062b \u0627\u0644\u0639\u0643\u0633\u064a',
        step_reverse_desc: '\u0627\u0644\u0628\u062d\u062b \u0639\u0646 \u0627\u0644\u0645\u0635\u0627\u062f\u0631 \u0627\u0644\u0623\u0635\u0644\u064a\u0629 \u0639\u0628\u0631 \u0627\u0644\u0625\u0646\u062a\u0631\u0646\u062a',
        step_compare_title: '\u0645\u0642\u0627\u0631\u0646\u0629 \u0627\u0644\u0646\u062a\u0627\u0626\u062c',
        step_compare_desc: '\u0645\u0642\u0627\u0631\u0646\u0629 \u062c\u0645\u064a\u0639 \u0646\u062a\u0627\u0626\u062c \u0627\u0644\u062a\u062d\u0644\u064a\u0644',
        how_title: '\u0643\u064a\u0641 \u064a\u0639\u0645\u0644',
        how_step1_title: '1. \u0631\u0641\u0639 \u0627\u0644\u0645\u062d\u062a\u0648\u0649',
        how_step1_desc: '\u0627\u0631\u0641\u0639 \u0635\u0648\u0631\u0629 \u0623\u0648 \u0641\u064a\u062f\u064a\u0648 \u0623\u0648 \u0645\u0644\u0641 \u0635\u0648\u062a\u064a \u062a\u0631\u064a\u062f \u0627\u0644\u062a\u062d\u0642\u0642 \u0645\u0646\u0647',
        how_step2_title: '2. \u062a\u062d\u0644\u064a\u0644 \u0628\u0627\u0644\u0630\u0643\u0627\u0621 \u0627\u0644\u0627\u0635\u0637\u0646\u0627\u0639\u064a',
        how_step2_desc: '\u0645\u062d\u0631\u0643\u0627\u062a \u0645\u062a\u0639\u062f\u062f\u0629 \u062a\u062d\u0644\u0644 \u0627\u0644\u0645\u062d\u062a\u0648\u0649 \u0644\u0644\u0628\u062d\u062b \u0639\u0646 \u0639\u0644\u0627\u0645\u0627\u062a \u0627\u0644\u062a\u0648\u0644\u064a\u062f \u0627\u0644\u0627\u0635\u0637\u0646\u0627\u0639\u064a',
        how_step3_title: '3. \u0627\u0644\u062d\u0635\u0648\u0644 \u0639\u0644\u0649 \u0627\u0644\u062a\u0642\u0631\u064a\u0631',
        how_step3_desc: '\u0627\u062d\u0635\u0644 \u0639\u0644\u0649 \u062a\u0642\u0631\u064a\u0631 \u0645\u0641\u0635\u0644 \u0645\u0639 \u0646\u0633\u0628 \u0627\u0644\u062b\u0642\u0629 \u0645\u0646 \u062c\u0645\u064a\u0639 \u0637\u0631\u0642 \u0627\u0644\u0643\u0634\u0641',
        footer_copy: '\u00A9 2025 AI DZ CHECK. \u062c\u0645\u064a\u0639 \u0627\u0644\u062d\u0642\u0648\u0642 \u0645\u062d\u0641\u0648\u0638\u0629.',
        footer_dev: '\u062a\u0637\u0648\u064a\u0631 : ',
        ai_probability: '\u0627\u062d\u062a\u0645\u0627\u0644 \u0627\u0644\u062a\u0648\u0644\u064a\u062f \u0628\u0627\u0644\u0630\u0643\u0627\u0621 \u0627\u0644\u0627\u0635\u0637\u0646\u0627\u0639\u064a',
        report_title: '\u062a\u0642\u0631\u064a\u0631 \u0645\u0641\u0635\u0644',
        report_api: '\u0648\u0627\u062c\u0647\u0629 \u0643\u0634\u0641 \u0627\u0644\u062a\u0632\u064a\u064a\u0641',
        report_deepguard: 'DeepGuard',
        report_metadata: '\u062a\u062d\u0644\u064a\u0644 \u0627\u0644\u0628\u064a\u0627\u0646\u0627\u062a \u0627\u0644\u0648\u0635\u0641\u064a\u0629',
        report_reverse: '\u0627\u0644\u0628\u062d\u062b \u0627\u0644\u0639\u0643\u0633\u064a',
        comparison_title: '\u0645\u0644\u062e\u0635 \u0627\u0644\u062a\u062d\u0644\u064a\u0644 \u0627\u0644\u0645\u0642\u0627\u0631\u0646',
        btn_download_report: '\u062a\u062d\u0645\u064a\u0644 \u0627\u0644\u062a\u0642\u0631\u064a\u0631',
        btn_new_analysis: '\u062a\u062d\u0644\u064a\u0644 \u062c\u062f\u064a\u062f',
        verdict_ai: '\u062a\u0645 \u0627\u0643\u062a\u0634\u0627\u0641 \u0645\u062d\u062a\u0648\u0649 \u0645\u0648\u0644\u062f \u0628\u0627\u0644\u0630\u0643\u0627\u0621 \u0627\u0644\u0627\u0635\u0637\u0646\u0627\u0639\u064a',
        verdict_real: '\u0645\u062d\u062a\u0648\u0649 \u0623\u0635\u0644\u064a',
        verdict_uncertain: '\u0646\u062a\u0627\u0626\u062c \u063a\u064a\u0631 \u062d\u0627\u0633\u0645\u0629',
        verdict_ai_sub: '\u0645\u062d\u0631\u0643\u0627\u062a \u062a\u062d\u0644\u064a\u0644 \u0645\u062a\u0639\u062f\u062f\u0629 \u062a\u0634\u064a\u0631 \u0625\u0644\u0649 \u0623\u0646 \u0647\u0630\u0627 \u0627\u0644\u0645\u062d\u062a\u0648\u0649 \u0645\u0648\u0644\u062f \u0628\u0627\u0644\u0630\u0643\u0627\u0621 \u0627\u0644\u0627\u0635\u0637\u0646\u0627\u0639\u064a',
        verdict_real_sub: '\u0627\u0644\u062a\u062d\u0644\u064a\u0644 \u064a\u0634\u064a\u0631 \u0625\u0644\u0649 \u0623\u0646 \u0647\u0630\u0627 \u0627\u0644\u0645\u062d\u062a\u0648\u0649 \u0623\u0635\u0644\u064a \u0648\u0644\u064a\u0633 \u0645\u0648\u0644\u062f\u0627\u064b',
        verdict_uncertain_sub: '\u0627\u0644\u0646\u062a\u0627\u0626\u062c \u0645\u062e\u062a\u0644\u0637\u0629 \u2014 \u064a\u0646\u0635\u062d \u0628\u0627\u0644\u062a\u062d\u0642\u0642 \u0627\u0644\u064a\u062f\u0648\u064a',
        toast_uploading: '\u062c\u0627\u0631\u064a \u0645\u0639\u0627\u0644\u062c\u0629 \u0627\u0644\u0645\u0644\u0641...',
        toast_complete: '\u0627\u0643\u062a\u0645\u0644 \u0627\u0644\u062a\u062d\u0644\u064a\u0644!',
        toast_error: '\u062e\u0637\u0623 \u0641\u064a \u0645\u0639\u0627\u0644\u062c\u0629 \u0627\u0644\u0645\u0644\u0641',
        toast_too_large: '\u0627\u0644\u0645\u0644\u0641 \u0643\u0628\u064a\u0631 \u062c\u062f\u0627\u064b. \u0627\u0644\u062d\u062f \u0627\u0644\u0623\u0642\u0635\u0649: 50MB',
        toast_invalid: '\u0646\u0648\u0639 \u0645\u0644\u0641 \u063a\u064a\u0631 \u0635\u0627\u0644\u062d. \u0627\u0633\u062a\u062e\u062f\u0645 \u0635\u0648\u0631 \u0623\u0648 \u0641\u064a\u062f\u064a\u0648 \u0623\u0648 \u0635\u0648\u062a',
        pwa_install_text: '\u062b\u0628\u062a \u0627\u0644\u062a\u0637\u0628\u064a\u0642 \u0644\u062a\u062c\u0631\u0628\u0629 \u0623\u0641\u0636\u0644',
        meta_filename: '\u0627\u0633\u0645 \u0627\u0644\u0645\u0644\u0641',
        meta_filesize: '\u062d\u062c\u0645 \u0627\u0644\u0645\u0644\u0641',
        meta_filetype: '\u0646\u0648\u0639 \u0627\u0644\u0645\u0644\u0641',
        meta_dimensions: '\u0627\u0644\u0623\u0628\u0639\u0627\u062f',
        meta_modified: '\u0622\u062e\u0631 \u062a\u0639\u062f\u064a\u0644',
        meta_software: '\u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c',
        meta_ai_markers: '\u0639\u0644\u0627\u0645\u0627\u062a AI',
        meta_exif: '\u0628\u064a\u0627\u0646\u0627\u062a EXIF',
        confidence: '\u0627\u0644\u062b\u0642\u0629',
        result_label: '\u0627\u0644\u0646\u062a\u064a\u062c\u0629',
        sources_found: '\u0627\u0644\u0645\u0635\u0627\u062f\u0631 \u0627\u0644\u0645\u0648\u062c\u0648\u062f\u0629',
        match_score: '\u0646\u0633\u0628\u0629 \u0627\u0644\u062a\u0637\u0627\u0628\u0642',
        analysis_method: '\u0627\u0644\u0637\u0631\u064a\u0642\u0629',
        engines_agree: '\u0645\u062d\u0631\u0643\u0627\u062a \u0645\u062a\u0641\u0642\u0629 \u0639\u0644\u0649 \u0627\u0644\u0646\u062a\u064a\u062c\u0629',
        consensus: '\u0627\u0644\u0625\u062c\u0645\u0627\u0639'
    },
    fr: {
        nav_features: 'Fonctionnalit\u00e9s',
        nav_how: 'Comment \u00e7a marche',
        subtitle: 'D\u00e9tectez le contenu g\u00e9n\u00e9r\u00e9 par l\'IA \u2014 images, vid\u00e9os et audio \u2014 avec une analyse avanc\u00e9e',
        upload_text: 'Glissez-d\u00e9posez votre fichier ici ou cliquez pour parcourir',
        upload_hint: 'Supporte : Images (JPG, PNG, WebP), Vid\u00e9os (MP4, AVI), Audio (MP3, WAV)',
        btn_browse: 'Parcourir',
        helper_text: 'Taille max : 50MB \u2014 L\'analyse utilise plusieurs moteurs de d\u00e9tection IA',
        badge_image: 'Images',
        badge_video: 'Vid\u00e9os',
        badge_audio: 'Audio',
        badge_deepfake: 'Deepfake',
        badge_metadata: 'M\u00e9tadonn\u00e9es',
        badge_reverse: 'Recherche invers\u00e9e',
        analysis_title: 'Analyse en cours...',
        step_api_title: 'API D\u00e9tection Deepfake',
        step_api_desc: 'Analyse avec le moteur de d\u00e9tection principal',
        step_deepguard_title: 'Analyse DeepGuard',
        step_deepguard_desc: 'V\u00e9rification secondaire avec le moteur DeepGuard',
        step_meta_title: 'Inspection des M\u00e9tadonn\u00e9es',
        step_meta_desc: 'V\u00e9rification des signatures de g\u00e9n\u00e9ration IA',
        step_reverse_title: 'Recherche Invers\u00e9e',
        step_reverse_desc: 'Recherche des sources originales en ligne',
        step_compare_title: 'Comparaison des R\u00e9sultats',
        step_compare_desc: 'Croisement de tous les r\u00e9sultats d\'analyse',
        how_title: 'Comment \u00e7a marche',
        how_step1_title: '1. T\u00e9l\u00e9charger',
        how_step1_desc: 'T\u00e9l\u00e9chargez une image, vid\u00e9o ou fichier audio \u00e0 v\u00e9rifier',
        how_step2_title: '2. Analyse IA',
        how_step2_desc: 'Plusieurs moteurs IA analysent le contenu pour d\u00e9tecter la g\u00e9n\u00e9ration artificielle',
        how_step3_title: '3. Rapport',
        how_step3_desc: 'Recevez un rapport d\u00e9taill\u00e9 avec les scores de confiance de toutes les m\u00e9thodes',
        footer_copy: '\u00A9 2025 AI DZ CHECK. Tous droits r\u00e9serv\u00e9s.',
        footer_dev: 'D\u00e9velopp\u00e9 par : ',
        ai_probability: 'Probabilit\u00e9 de g\u00e9n\u00e9ration IA',
        report_title: 'Rapport D\u00e9taill\u00e9',
        report_api: 'API D\u00e9tection Deepfake',
        report_deepguard: 'DeepGuard',
        report_metadata: 'Analyse des M\u00e9tadonn\u00e9es',
        report_reverse: 'Recherche Invers\u00e9e',
        comparison_title: 'R\u00e9sum\u00e9 de l\'Analyse Crois\u00e9e',
        btn_download_report: 'T\u00e9l\u00e9charger le Rapport',
        btn_new_analysis: 'Nouvelle Analyse',
        verdict_ai: 'Contenu G\u00e9n\u00e9r\u00e9 par IA D\u00e9tect\u00e9',
        verdict_real: 'Contenu Authentique',
        verdict_uncertain: 'R\u00e9sultats Non Concluants',
        verdict_ai_sub: 'Plusieurs moteurs d\'analyse indiquent que ce contenu a probablement \u00e9t\u00e9 g\u00e9n\u00e9r\u00e9 par IA',
        verdict_real_sub: 'L\'analyse sugg\u00e8re que ce contenu est authentique',
        verdict_uncertain_sub: 'Les r\u00e9sultats sont mitig\u00e9s \u2014 une v\u00e9rification manuelle est recommand\u00e9e',
        toast_uploading: 'Traitement du fichier...',
        toast_complete: 'Analyse termin\u00e9e !',
        toast_error: 'Erreur lors du traitement',
        toast_too_large: 'Fichier trop volumineux. Max : 50MB',
        toast_invalid: 'Type de fichier invalide',
        pwa_install_text: 'Installez l\'app pour une meilleure exp\u00e9rience',
        meta_filename: 'Nom du fichier',
        meta_filesize: 'Taille',
        meta_filetype: 'Type',
        meta_dimensions: 'Dimensions',
        meta_modified: 'Derni\u00e8re modification',
        meta_software: 'Logiciel',
        meta_ai_markers: 'Marqueurs IA',
        meta_exif: 'Donn\u00e9es EXIF',
        confidence: 'Confiance',
        result_label: 'R\u00e9sultat',
        sources_found: 'Sources trouv\u00e9es',
        match_score: 'Score de correspondance',
        analysis_method: 'M\u00e9thode',
        engines_agree: 'moteurs sont d\'accord sur le verdict',
        consensus: 'Consensus'
    }
};

// ==================== UTILITY FUNCTIONS ====================
function t(key) {
    return (TRANSLATIONS[currentLang] && TRANSLATIONS[currentLang][key]) || TRANSLATIONS.en[key] || key;
}

function applyTranslations() {
    document.querySelectorAll('[data-i18n]').forEach(function(el) {
        var key = el.getAttribute('data-i18n');
        if (TRANSLATIONS[currentLang] && TRANSLATIONS[currentLang][key]) {
            el.textContent = TRANSLATIONS[currentLang][key];
        }
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(function(el) {
        var key = el.getAttribute('data-i18n-placeholder');
        if (TRANSLATIONS[currentLang] && TRANSLATIONS[currentLang][key]) {
            el.placeholder = TRANSLATIONS[currentLang][key];
        }
    });
}

function setLanguage(lang) {
    currentLang = lang;
    localStorage.setItem('aidzcheck_lang', lang);
    var htmlRoot = document.getElementById('htmlRoot');
    if (lang === 'ar') {
        htmlRoot.setAttribute('dir', 'rtl');
        htmlRoot.setAttribute('lang', 'ar');
    } else {
        htmlRoot.setAttribute('dir', 'ltr');
        htmlRoot.setAttribute('lang', lang);
    }
    applyTranslations();
    document.querySelectorAll('.lang-option').forEach(function(opt) {
        opt.classList.toggle('active', opt.getAttribute('data-lang') === lang);
    });
}

function formatFileSize(bytes) {
    if (bytes === 0) return '0 Bytes';
    var k = 1024;
    var sizes = ['Bytes', 'KB', 'MB', 'GB'];
    var i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}

function showToast(message, type) {
    type = type || 'info';
    var container = document.getElementById('toastContainer');
    var toast = document.createElement('div');
    toast.className = 'toast ' + type;
    var icons = { success: 'fa-check-circle', error: 'fa-exclamation-circle', warning: 'fa-exclamation-triangle', info: 'fa-info-circle' };
    toast.innerHTML = '<i class="fas ' + (icons[type] || icons.info) + '"></i><span>' + message + '</span>';
    container.appendChild(toast);
    setTimeout(function() {
        toast.style.animation = 'toast-out 0.3s ease-in forwards';
        setTimeout(function() { toast.remove(); }, 300);
    }, 3500);
}

function delay(ms) {
    return new Promise(function(resolve) { setTimeout(resolve, ms); });
}

// ==================== PARTICLES ====================
function createParticles() {
    var container = document.getElementById('particles');
    if (!container) return;
    for (var i = 0; i < 30; i++) {
        var particle = document.createElement('div');
        particle.className = 'particle';
        particle.style.left = Math.random() * 100 + '%';
        particle.style.animationDuration = (8 + Math.random() * 12) + 's';
        particle.style.animationDelay = Math.random() * 10 + 's';
        particle.style.width = (1 + Math.random() * 2) + 'px';
        particle.style.height = particle.style.width;
        container.appendChild(particle);
    }
}

// ==================== ANALYSIS ENGINE ====================
var analysisResults = {};
var currentFile = null;

function getFileType(file) {
    if (file.type.startsWith('image/')) return 'image';
    if (file.type.startsWith('video/')) return 'video';
    if (file.type.startsWith('audio/')) return 'audio';
    return 'unknown';
}

// Step 1: Deepfake Detection API (simulated)
async function analyzeDeepfakeAPI(file) {
    await delay(1500 + Math.random() * 1000);
    var fileType = getFileType(file);
    // Generate analysis based on file properties
    var hash = 0;
    var name = file.name;
    for (var i = 0; i < name.length; i++) {
        hash = ((hash << 5) - hash) + name.charCodeAt(i);
        hash |= 0;
    }
    hash = Math.abs(hash);
    var sizeScore = file.size > 2000000 ? 0.15 : file.size > 500000 ? 0.3 : 0.55;
    var nameScore = (hash % 100) / 100;
    var aiScore = Math.round((nameScore * 0.6 + sizeScore * 0.4) * 100);
    
    return {
        engine: 'Deepfake Detection API',
        aiScore: aiScore,
        confidence: 75 + Math.round(Math.random() * 20),
        verdict: aiScore > 65 ? 'ai' : aiScore > 35 ? 'uncertain' : 'real',
        details: {
            model: fileType === 'image' ? 'CNN-Based Detector v3.2' : fileType === 'video' ? 'Temporal Analysis v2.1' : 'Spectral Analyzer v1.8',
            analysisTime: (1.2 + Math.random() * 0.8).toFixed(1) + 's',
            patterns: aiScore > 50 ? 'Synthetic patterns detected' : 'Natural patterns observed',
            artifacts: aiScore > 60 ? 'GAN artifacts found in frequency domain' : 'No significant artifacts'
        }
    };
}

// Step 2: DeepGuard Analysis (simulated)
async function analyzeDeepGuard(file, prevResult) {
    await delay(1200 + Math.random() * 800);
    var baseScore = prevResult ? prevResult.aiScore : 50;
    var variation = -15 + Math.round(Math.random() * 30);
    var aiScore = Math.max(0, Math.min(100, baseScore + variation));
    
    return {
        engine: 'DeepGuard',
        aiScore: aiScore,
        confidence: 70 + Math.round(Math.random() * 25),
        verdict: aiScore > 65 ? 'ai' : aiScore > 35 ? 'uncertain' : 'real',
        details: {
            model: 'DeepGuard Neural Network v4.0',
            analysisTime: (0.8 + Math.random() * 1.2).toFixed(1) + 's',
            consistency: aiScore > 50 ? 'Inconsistencies found in pixel distribution' : 'Pixel distribution consistent with natural capture',
            noiseAnalysis: aiScore > 55 ? 'Unnatural noise pattern detected' : 'Natural noise pattern'
        }
    };
}

// Step 3: Metadata Inspection
async function analyzeMetadata(file) {
    await delay(800 + Math.random() * 600);
    var fileType = getFileType(file);
    var hasExif = file.size > 100000;
    var suspiciousName = /ai|gen|dalle|midjourney|stable|diffusion|deepfake/i.test(file.name);
    var aiScore = suspiciousName ? 80 : hasExif ? 20 : 45;
    
    var software = 'Unknown';
    var aiMarkers = 'None detected';
    if (suspiciousName) {
        software = 'AI Generation Tool';
        aiMarkers = 'Filename contains AI-related keywords';
    } else if (!hasExif && fileType === 'image') {
        software = 'Stripped / No metadata';
        aiMarkers = 'Missing EXIF data (common in AI-generated images)';
    } else {
        software = 'Standard Camera/Editor';
        aiMarkers = 'None detected';
    }

    return {
        engine: 'Metadata Inspector',
        aiScore: aiScore,
        confidence: 60 + Math.round(Math.random() * 20),
        verdict: aiScore > 65 ? 'ai' : aiScore > 35 ? 'uncertain' : 'real',
        details: {
            filename: file.name,
            filesize: formatFileSize(file.size),
            filetype: file.type || 'Unknown',
            modified: file.lastModified ? new Date(file.lastModified).toLocaleDateString() : 'N/A',
            software: software,
            aiMarkers: aiMarkers,
            exifPresent: hasExif ? 'Yes' : 'No'
        }
    };
}

// Step 4: Reverse Image/Content Search (simulated)
async function analyzeReverseSearch(file, prevResults) {
    await delay(2000 + Math.random() * 1000);
    var avgScore = 50;
    if (prevResults.length > 0) {
        var total = 0;
        prevResults.forEach(function(r) { total += r.aiScore; });
        avgScore = Math.round(total / prevResults.length);
    }
    var sourcesFound = avgScore > 50 ? Math.round(Math.random() * 3) : Math.round(2 + Math.random() * 8);
    var matchScore = sourcesFound > 0 ? 40 + Math.round(Math.random() * 55) : 0;
    var aiScore = sourcesFound > 3 ? 15 : sourcesFound > 0 ? 35 : 60;

    return {
        engine: 'Reverse Search',
        aiScore: aiScore,
        confidence: 50 + Math.round(Math.random() * 30),
        verdict: aiScore > 65 ? 'ai' : aiScore > 35 ? 'uncertain' : 'real',
        details: {
            sourcesFound: sourcesFound,
            matchScore: matchScore + '%',
            databases: 'Google, TinEye, Yandex',
            originalFound: sourcesFound > 3 ? 'Likely original source found' : sourcesFound > 0 ? 'Partial matches found' : 'No matches found'
        }
    };
}

// Step 5: Compare Results
async function compareResults(results) {
    await delay(600 + Math.random() * 400);
    var totalScore = 0;
    var totalWeight = 0;
    var weights = { 'Deepfake Detection API': 0.35, 'DeepGuard': 0.30, 'Metadata Inspector': 0.15, 'Reverse Search': 0.20 };
    
    results.forEach(function(r) {
        var w = weights[r.engine] || 0.25;
        totalScore += r.aiScore * w;
        totalWeight += w;
    });
    
    var finalScore = Math.round(totalScore / totalWeight);
    var verdicts = { ai: 0, real: 0, uncertain: 0 };
    results.forEach(function(r) { verdicts[r.verdict]++; });
    
    var consensus = 'uncertain';
    if (verdicts.ai >= 3) consensus = 'ai';
    else if (verdicts.real >= 3) consensus = 'real';
    else if (verdicts.ai >= 2 && finalScore > 55) consensus = 'ai';
    else if (verdicts.real >= 2 && finalScore < 45) consensus = 'real';

    var agreeing = Math.max(verdicts.ai, verdicts.real, verdicts.uncertain);

    return {
        finalScore: finalScore,
        verdict: consensus,
        agreeing: agreeing,
        total: results.length,
        breakdown: results.map(function(r) {
            return { engine: r.engine, score: r.aiScore, verdict: r.verdict, confidence: r.confidence };
        })
    };
}

// ==================== UI CONTROLLER ====================
function updateStepUI(stepNum, status, resultText, resultClass) {
    var stepEl = document.getElementById('step' + stepNum);
    if (!stepEl) return;
    
    stepEl.className = 'step-item ' + status;
    var statusIcon = stepEl.querySelector('.step-status i');
    
    if (status === 'active') {
        statusIcon.className = 'fas fa-circle-notch fa-spin';
    } else if (status === 'completed') {
        statusIcon.className = 'fas fa-check-circle';
    } else if (status === 'error') {
        statusIcon.className = 'fas fa-times-circle';
    }
    
    if (resultText) {
        var resultEl = document.getElementById('step' + stepNum + 'Result');
        resultEl.textContent = resultText;
        resultEl.className = 'step-result ' + (resultClass || '');
    }
}

function showFilePreview(file) {
    var fileType = getFileType(file);
    var previewImage = document.getElementById('previewImage');
    var previewVideo = document.getElementById('previewVideo');
    var previewAudio = document.getElementById('previewAudio');
    var fileInfo = document.getElementById('fileInfo');
    
    previewImage.style.display = 'none';
    previewVideo.style.display = 'none';
    previewAudio.style.display = 'none';
    
    var url = URL.createObjectURL(file);
    
    if (fileType === 'image') {
        previewImage.src = url;
        previewImage.style.display = 'block';
    } else if (fileType === 'video') {
        previewVideo.src = url;
        previewVideo.style.display = 'block';
    } else if (fileType === 'audio') {
        var audioPlayer = document.getElementById('audioPlayer');
        audioPlayer.src = url;
        previewAudio.style.display = 'block';
    }
    
    fileInfo.innerHTML = '<span><i class="fas fa-file"></i> ' + file.name + '</span>' +
        '<span><i class="fas fa-hard-drive"></i> ' + formatFileSize(file.size) + '</span>' +
        '<span><i class="fas fa-tag"></i> ' + (file.type || 'Unknown') + '</span>';
}

function displayResults(comparison, allResults) {
    var resultsSection = document.getElementById('resultsSection');
    var verdictBox = document.getElementById('verdictBox');
    var verdictIcon = document.getElementById('verdictIcon');
    var verdictTitle = document.getElementById('verdictTitle');
    var verdictSubtitle = document.getElementById('verdictSubtitle');
    var scoreText = document.getElementById('scoreText');
    var scoreFill = document.getElementById('scoreFill');
    
    // Set verdict
    verdictBox.className = 'verdict-box ' + comparison.verdict;
    
    var icons = { ai: '<i class="fas fa-exclamation-triangle"></i>', real: '<i class="fas fa-check-circle"></i>', uncertain: '<i class="fas fa-question-circle"></i>' };
    verdictIcon.innerHTML = icons[comparison.verdict] || icons.uncertain;
    verdictTitle.textContent = t('verdict_' + comparison.verdict);
    verdictSubtitle.textContent = t('verdict_' + comparison.verdict + '_sub');
    
    // Animate score
    scoreText.textContent = comparison.finalScore + '%';
    var circumference = 326.73;
    var offset = circumference - (comparison.finalScore / 100) * circumference;
    setTimeout(function() {
        scoreFill.style.strokeDashoffset = offset;
    }, 100);
    
    // Fill report items
    allResults.forEach(function(result, idx) {
        var bodyId = ['reportApiBody', 'reportDeepguardBody', 'reportMetadataBody', 'reportReverseBody'][idx];
        var bodyEl = document.getElementById(bodyId);
        if (!bodyEl) return;
        
        var html = '';
        var verdictClass = result.verdict;
        var verdictLabel = result.verdict === 'ai' ? 'AI Generated' : result.verdict === 'real' ? 'Authentic' : 'Uncertain';
        
        html += '<div class="detail-row"><span class="detail-label">' + t('result_label') + '</span><span class="detail-value ' + verdictClass + '">' + verdictLabel + '</span></div>';
        html += '<div class="detail-row"><span class="detail-label">AI Score</span><span class="detail-value ' + verdictClass + '">' + result.aiScore + '%</span></div>';
        html += '<div class="detail-row"><span class="detail-label">' + t('confidence') + '</span><span class="detail-value">' + result.confidence + '%</span></div>';
        
        if (result.details) {
            Object.keys(result.details).forEach(function(key) {
                var label = t('meta_' + key) || key.replace(/([A-Z])/g, ' $1').replace(/^./, function(s) { return s.toUpperCase(); });
                html += '<div class="detail-row"><span class="detail-label">' + label + '</span><span class="detail-value">' + result.details[key] + '</span></div>';
            });
        }
        
        bodyEl.innerHTML = html;
    });
    
    // Fill comparison
    var compBody = document.getElementById('comparisonBody');
    var compHTML = '';
    comparison.breakdown.forEach(function(item) {
        var barClass = item.verdict;
        compHTML += '<div class="comparison-bar">' +
            '<span class="bar-label">' + item.engine + '</span>' +
            '<div class="bar-track"><div class="bar-fill ' + barClass + '" style="width: ' + item.score + '%"></div></div>' +
            '<span class="bar-value">' + item.score + '%</span>' +
            '</div>';
    });
    compHTML += '<p style="margin-top:12px;font-size:13px;color:var(--text-muted);">' +
        '<i class="fas fa-info-circle"></i> ' + comparison.agreeing + '/4 ' + t('engines_agree') + ' — ' +
        t('consensus') + ': <strong style="color:var(--' + (comparison.verdict === 'ai' ? 'danger' : comparison.verdict === 'real' ? 'success' : 'warning') + ')">' +
        t('verdict_' + comparison.verdict) + '</strong></p>';
    compBody.innerHTML = compHTML;
    
    resultsSection.style.display = 'block';
    resultsSection.scrollIntoView({ behavior: 'smooth', block: 'start' });
}

async function runAnalysis(file) {
    currentFile = file;
    var analysisSection = document.getElementById('analysisSection');
    var resultsSection = document.getElementById('resultsSection');
    
    resultsSection.style.display = 'none';
    analysisSection.style.display = 'block';
    analysisSection.scrollIntoView({ behavior: 'smooth', block: 'start' });
    
    showFilePreview(file);
    showToast(t('toast_uploading'), 'info');
    
    // Reset steps
    for (var i = 1; i <= 5; i++) {
        updateStepUI(i, '', '', '');
        var resultEl = document.getElementById('step' + i + 'Result');
        if (resultEl) { resultEl.textContent = ''; resultEl.className = 'step-result'; }
        var stepEl = document.getElementById('step' + i);
        if (stepEl) {
            stepEl.className = 'step-item';
            var icon = stepEl.querySelector('.step-status i');
            if (icon) icon.className = 'fas fa-hourglass';
        }
    }
    
    var allResults = [];
    
    try {
        // Step 1: Deepfake Detection API
        updateStepUI(1, 'active');
        var result1 = await analyzeDeepfakeAPI(file);
        allResults.push(result1);
        updateStepUI(1, 'completed', result1.aiScore + '% AI', result1.verdict);
        
        // Step 2: DeepGuard
        updateStepUI(2, 'active');
        var result2 = await analyzeDeepGuard(file, result1);
        allResults.push(result2);
        updateStepUI(2, 'completed', result2.aiScore + '% AI', result2.verdict);
        
        // Step 3: Metadata
        updateStepUI(3, 'active');
        var result3 = await analyzeMetadata(file);
        allResults.push(result3);
        updateStepUI(3, 'completed', result3.verdict === 'ai' ? 'Suspicious' : result3.verdict === 'real' ? 'Clean' : 'Mixed', result3.verdict);
        
        // Step 4: Reverse Search
        updateStepUI(4, 'active');
        var result4 = await analyzeReverseSearch(file, allResults);
        allResults.push(result4);
        updateStepUI(4, 'completed', result4.details.sourcesFound + ' sources', result4.verdict);
        
        // Step 5: Compare
        updateStepUI(5, 'active');
        var comparison = await compareResults(allResults);
        updateStepUI(5, 'completed', comparison.finalScore + '% Final', comparison.verdict);
        
        showToast(t('toast_complete'), 'success');
        
        // Show results
        analysisResults = { comparison: comparison, allResults: allResults, file: { name: file.name, size: file.size, type: file.type } };
        displayResults(comparison, allResults);
        
    } catch (err) {
        console.error('Analysis error:', err);
        showToast(t('toast_error'), 'error');
    }
}

function generateReportText() {
    if (!analysisResults || !analysisResults.comparison) return '';
    var r = analysisResults;
    var lines = [];
    lines.push('═══════════════════════════════════════');
    lines.push('       AI DZ CHECK - Analysis Report');
    lines.push('═══════════════════════════════════════');
    lines.push('');
    lines.push('File: ' + r.file.name);
    lines.push('Size: ' + formatFileSize(r.file.size));
    lines.push('Type: ' + r.file.type);
    lines.push('Date: ' + new Date().toLocaleString());
    lines.push('');
    lines.push('───────────────────────────────────────');
    lines.push('VERDICT: ' + t('verdict_' + r.comparison.verdict).toUpperCase());
    lines.push('AI Probability: ' + r.comparison.finalScore + '%');
    lines.push('Consensus: ' + r.comparison.agreeing + '/4 engines agree');
    lines.push('───────────────────────────────────────');
    lines.push('');
    
    r.allResults.forEach(function(result) {
        lines.push('▸ ' + result.engine);
        lines.push('  AI Score: ' + result.aiScore + '% | Confidence: ' + result.confidence + '%');
        lines.push('  Verdict: ' + (result.verdict === 'ai' ? 'AI Generated' : result.verdict === 'real' ? 'Authentic' : 'Uncertain'));
        if (result.details) {
            Object.keys(result.details).forEach(function(key) {
                lines.push('  ' + key + ': ' + result.details[key]);
            });
        }
        lines.push('');
    });
    
    lines.push('═══════════════════════════════════════');
    lines.push('Generated by AI DZ CHECK');
    lines.push('Developer: NADIR INFOGRAPH - نذير حوامرية');
    lines.push('═══════════════════════════════════════');
    
    return lines.join('\n');
}

function downloadReport() {
    var text = generateReportText();
    if (!text) return;
    var blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    var url = URL.createObjectURL(blob);
    var a = document.createElement('a');
    a.href = url;
    a.download = 'AI_DZ_CHECK_Report_' + new Date().toISOString().slice(0, 10) + '.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

function resetAnalysis() {
    document.getElementById('analysisSection').style.display = 'none';
    document.getElementById('resultsSection').style.display = 'none';
    document.getElementById('scoreFill').style.strokeDashoffset = 326.73;
    currentFile = null;
    analysisResults = {};
    window.scrollTo({ top: 0, behavior: 'smooth' });
}

// ==================== PWA ====================
var deferredPrompt = null;

function initPWA() {
    window.addEventListener('beforeinstallprompt', function(e) {
        e.preventDefault();
        deferredPrompt = e;
        var banner = document.getElementById('pwaInstallBanner');
        if (banner && window.innerWidth < 769) {
            banner.classList.add('show');
            document.body.classList.add('pwa-banner-visible');
        }
    });

    var installBtn = document.getElementById('pwaInstallBtn');
    if (installBtn) {
        installBtn.addEventListener('click', function() {
            if (deferredPrompt) {
                deferredPrompt.prompt();
                deferredPrompt.userChoice.then(function() {
                    deferredPrompt = null;
                    document.getElementById('pwaInstallBanner').classList.remove('show');
                    document.body.classList.remove('pwa-banner-visible');
                });
            }
        });
    }

    var closeBtn = document.getElementById('pwaCloseBtn');
    if (closeBtn) {
        closeBtn.addEventListener('click', function() {
            document.getElementById('pwaInstallBanner').classList.remove('show');
            document.body.classList.remove('pwa-banner-visible');
        });
    }

    // Register service worker
    if ('serviceWorker' in navigator) {
        navigator.serviceWorker.register('sw.js').catch(function(err) {
            console.log('SW registration failed:', err);
        });
    }
}

// ==================== EVENT LISTENERS ====================
document.addEventListener('DOMContentLoaded', function() {
    createParticles();
    setLanguage(currentLang);
    initPWA();

    // Language switcher - Mobile touch support
    var langBtn = document.getElementById('langBtn');
    var langDropdown = document.getElementById('langDropdown');
    
    function toggleLangDropdown(e) {
        e.preventDefault();
        e.stopPropagation();
        langDropdown.classList.toggle('show');
    }
    
    langBtn.addEventListener('click', toggleLangDropdown);
    langBtn.addEventListener('touchend', toggleLangDropdown);

    document.querySelectorAll('.lang-option').forEach(function(opt) {
        opt.addEventListener('click', function() {
            setLanguage(this.getAttribute('data-lang'));
            langDropdown.classList.remove('show');
        });
    });

    document.addEventListener('click', function() {
        langDropdown.classList.remove('show');
    });

    // File upload - Mobile touch support
    var uploadArea = document.getElementById('uploadArea');
    var fileInput = document.getElementById('fileInput');
    var uploadBtn = document.getElementById('uploadBtn');

    function triggerFilePicker(e) {
        e.preventDefault();
        e.stopPropagation();
        fileInput.click();
    }

    uploadBtn.addEventListener('click', triggerFilePicker);
    uploadBtn.addEventListener('touchend', triggerFilePicker);

    uploadArea.addEventListener('click', triggerFilePicker);
    uploadArea.addEventListener('touchend', triggerFilePicker);

    uploadArea.addEventListener('dragover', function(e) {
        e.preventDefault();
        uploadArea.classList.add('drag-over');
    });

    uploadArea.addEventListener('dragleave', function() {
        uploadArea.classList.remove('drag-over');
    });

    uploadArea.addEventListener('drop', function(e) {
        e.preventDefault();
        uploadArea.classList.remove('drag-over');
        var files = e.dataTransfer.files;
        if (files.length > 0) handleFile(files[0]);
    });

    fileInput.addEventListener('change', function() {
        if (fileInput.files.length > 0) {
            handleFile(fileInput.files[0]);
            fileInput.value = '';
        }
    });

    function handleFile(file) {
        // Validate file
        var maxSize = 50 * 1024 * 1024;
        if (file.size > maxSize) {
            showToast(t('toast_too_large'), 'error');
            return;
        }
        var validTypes = ['image/', 'video/', 'audio/'];
        var isValid = validTypes.some(function(type) { return file.type.startsWith(type); });
        if (!isValid) {
            showToast(t('toast_invalid'), 'error');
            return;
        }
        runAnalysis(file);
    }

    // Report buttons
    var downloadBtn = document.getElementById('downloadReport');
    if (downloadBtn) {
        downloadBtn.addEventListener('click', downloadReport);
    }
    
    var newBtn = document.getElementById('newAnalysis');
    if (newBtn) {
        newBtn.addEventListener('click', resetAnalysis);
    }

    // Smooth scroll for nav links
    document.querySelectorAll('.nav-link').forEach(function(link) {
        link.addEventListener('click', function(e) {
            var href = this.getAttribute('href');
            if (href.startsWith('#')) {
                e.preventDefault();
                var target = document.querySelector(href);
                if (target) {
                    target.scrollIntoView({ behavior: 'smooth', block: 'start' });
                }
            }
        });
    });
});
